version = 1

test_patterns = [
  "**/test/**",
  "**/tests/**"
]

exclude_patterns = [
  "**/lib/**",
  "**/**.min.js"
]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  module_system = "amd"
  environment = [
    "jquery",
    "browser"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "black"
